spring:
  application:
    name: shop-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://localhost:8889
  cloud:
    config:
      label: 004-Async-communication
